import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Handshake, Users } from 'lucide-react';
import api from '../utils/api';
import { toast } from 'react-toastify';

const HandshakeModal = ({ isOpen, onClose }) => {
  const [activeTab, setActiveTab] = useState('generate'); // generate | enter
  const [code, setCode] = useState('');
  const [inputCode, setInputCode] = useState('');
  const [loading, setLoading] = useState(false);

  const generateCode = async () => {
    try {
      setLoading(true);
      const res = await api.post('/connections/generate', {}, {
        headers: { Authorization: `Bearer ${localStorage.getItem('makiToken')}` }
      });
      setCode(res.data.code);
    } catch (err) {
      toast.error('Failed to generate code.');
    } finally {
      setLoading(false);
    }
  };

  const submitCode = async () => {
    if (inputCode.length !== 6) {
      toast.error('Code must be 6 digits.');
      return;
    }
    try {
      setLoading(true);
      await api.post('/connections/verify', { code: inputCode }, {
        headers: { Authorization: `Bearer ${localStorage.getItem('makiToken')}` }
      });
      toast.success('Connection established successfully!');
      onClose();
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to verify code.');
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[60] flex items-center justify-center px-4 bg-brown-900/40 backdrop-blur-sm">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="bg-white rounded-3xl p-6 w-full max-w-md shadow-xl relative overflow-hidden"
        >
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-bold text-brown-900 flex items-center gap-2">
              <Handshake className="text-brown-500" />
              Maki Handshake
            </h2>
            <button onClick={onClose} className="p-2 text-brown-400 hover:text-brown-700 hover:bg-brown-50 rounded-full transition-colors">
              <X size={20} />
            </button>
          </div>

          <div className="flex gap-2 mb-6 p-1 bg-brown-50 rounded-xl">
            <button
              onClick={() => setActiveTab('generate')}
              className={`flex-1 py-2 text-sm font-semibold rounded-lg transition-colors ${activeTab === 'generate' ? 'bg-white text-brown-900 shadow-sm' : 'text-brown-500 hover:text-brown-700'}`}
            >
              My Code
            </button>
            <button
              onClick={() => setActiveTab('enter')}
              className={`flex-1 py-2 text-sm font-semibold rounded-lg transition-colors ${activeTab === 'enter' ? 'bg-white text-brown-900 shadow-sm' : 'text-brown-500 hover:text-brown-700'}`}
            >
              Enter Code
            </button>
          </div>

          {activeTab === 'generate' ? (
            <div className="text-center py-4">
              <p className="text-sm text-brown-600 mb-6">Generate a secure 6-digit code to share with someone you've met.</p>

              {code ? (
                <div className="mb-6">
                  <div className="text-4xl font-mono font-bold tracking-widest text-brown-800 bg-brown-50 py-4 rounded-xl border border-brown-200">
                    {code}
                  </div>
                  <p className="text-xs text-brown-400 mt-2">Code expires in 5 minutes.</p>
                </div>
              ) : (
                <button
                  onClick={generateCode}
                  disabled={loading}
                  className="w-full py-3 bg-brown-600 hover:bg-brown-700 text-white font-bold rounded-xl transition-colors shadow-sm disabled:opacity-70"
                >
                  {loading ? 'Generating...' : 'Generate Code'}
                </button>
              )}
            </div>
          ) : (
            <div className="text-center py-4">
               <p className="text-sm text-brown-600 mb-6">Enter a code generated by another user to establish a connection.</p>
               <input
                  type="text"
                  maxLength={6}
                  value={inputCode}
                  onChange={(e) => setInputCode(e.target.value.replace(/\D/g, ''))}
                  placeholder="000000"
                  className="w-full text-center text-3xl font-mono font-bold tracking-widest text-brown-800 bg-brown-50 py-4 rounded-xl border border-brown-200 focus:outline-none focus:border-brown-400 mb-6"
               />
               <button
                  onClick={submitCode}
                  disabled={loading || inputCode.length !== 6}
                  className="w-full py-3 bg-brown-600 hover:bg-brown-700 text-white font-bold rounded-xl transition-colors shadow-sm disabled:opacity-70"
                >
                  {loading ? 'Verifying...' : 'Establish Connection'}
                </button>
            </div>
          )}

        </motion.div>
      </div>
    </AnimatePresence>
  );
};

export default HandshakeModal;
